version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - redis

  celery:
    build: ./app
    command: celery --app=hello_django worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./app:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis

  redis:
    image: redis:7-alpine

  dashboard:
    build: ./app
    command: celery flower -A hello_django --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    env_file:
        - ./.env.dev
    depends_on:
      - web
      - redis
      - celery

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
