# Generated by Django 4.2.3 on 2024-03-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_one', models.CharField(max_length=550)),
                ('param_two', models.CharField(max_length=550)),
                ('param_three', models.CharField(max_length=550)),
                ('param_four', models.CharField(max_length=550)),
                ('param_five', models.CharField(max_length=550)),
            ],
        ),
    ]
